title: Automate Sketch
author: Ashung Hung
email: Ashung.hung@foxmail.com
keywords: [sketch, plugin, sketchplugin]
description: "Make Sketch more efficient -- a lot of useful plugins in one."
baseurl: ""
ghpageUrl: "http://ashung.github.io/Automate-Sketch/"
projectUrl: "https://github.com/Ashung/Automate-Sketch/"
issuesUrl: "https://github.com/Ashung/Automate-Sketch/issues/"
